# Generated by Django 3.1.7 on 2021-03-09 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('course_num', models.IntegerField(blank=True)),
                ('instructor_name', models.CharField(blank=True, default='', max_length=50)),
                ('duration', models.FloatField(blank=True, max_length=5)),
            ],
        ),
    ]
